### ISSUE TITLE
i3menu: line 83:  4423 Segmentation fault

### ISSUE THREAD

**Issue by metapodcod** [budlabs/i3ass#177]
```
i3menu --theme red
/usr/bin/i3menu: line 83:  4423 Segmentation fault      (core dumped) "${_menu_command[@]}" -theme <(themefile)
```

Can you give more detailed information about its use?

**Comment by budRich** [comment]
sorry you are having these issues. I noticed similar issues myself, and tracked many of them to **rofi**. I have actually been working on a replacement for rofi as a i3menu dependency. A fork of dmenu capable of everything needed.

But, adding this dmenu fork as a dependency to i3menu, means it becomes a dependency for i3ass. I think what i will do is move i3menu out of i3ass into its own repo, and publish the dmenu for (3menu ?) separately. 

This will happen soon, thanks for the issue, it reminded me i need to get back on it (i am actually using the new alternative myself, so i don't cause my own issues.)

**Comment by 1ntronaut** [comment]
> ```
  > i3menu --theme red
  > /usr/bin/i3menu: line 83:  4423 Segmentation fault      (core dumped) "${_menu_command[@]}" -theme <(themefile)
  > ```
  > 
  > Can you give more detailed information about its use?
  
  Hi Metapodcod, Hi budRich
  
> I had been typing quite a long guide to provide you with the most complete info possible, but I got confused.
> However, I did manage to fix the segmentation fault.

  I have been having the exact same segfault problem for quite a while now, however I did notice that i3menu sometimes decides to pass some options anyway.
  
  I also noticed that when i3menu was called from the i3term script, it would work basically flawless... I copied the command from /usr/bin/i3term into a terminal, and it worked!
  
  I have been looking/thinking about how to handle that segfault ;  as I do actually like i3menu a lot, especially (with or without i3fyra) the flexible positioning around the i3 workspace (tab, titlebar, window, x- and y- and offset).
  
  Regardless, I managed to resolve this issue with just about the easiest fix imaginable:
  
  - edit your  `i3menu` binary/script (use `which i3menu` if you're not sure); it's usually in /usr/bin/i3menu (if you installed i3ass using the makefile via AUR or manually with git)
  - sudo open binary with your favorite text editor, like so:
  
  ```bash
  sudo nvim $(which i3menu)
  ```
  - search for the line containing '-theme' (for me it actually turned out to be line 73), you only need to add an extra dash ( ` - ` ) in front of `-theme`, like so:
- original:    `((_o[dryrun]))  || "${_menu_command[@]}" -theme <(themefile)`
- bugfixed:  `((_o[dryrun]))  || "${_menu_command[@]}" --theme <(themefile)`

To be honest, this was a toal shot in the dark for me, I know some of the syntax and roughly how the i3ass-scripts work together... so I made a gues, and now I don't have any segfaults anymore at all.
I thought I'd made some sort of dirty quicdk fix, but it all seems fine now...


HOWEVER: there is maybe more you should know, I noticed - by accident - that it can still end up breaking when trying out themes.. I am not sure what it is exactly, and I unfortunately don't have the time to go through all of it.

But I believe rofi will sometimes throw an error if $XDG_DATA_DIRS is not defined / in your environment variables.
AND/OR maybe you will need to add rofi's themes folder to your $PATH variable ( dirs are:   /usr/share/rofi/themes:$HOME/.config/rofi/themes )

The main binary works again, but I'm not sure if it'll stay that way when I end up customizing configs/themes/directory structure.

- - - -
anyhow, quite some text for a little fix -- but I hope it helped

Cheers
~intronaut

**Comment by budRich** [comment]
@1ntronaut thanks, i will patch i3menu with your bugfix. Rofi must have changed their cli-syntax from `-theme` to `--theme` at some point.

**Comment by 1ntronaut** [comment]
@budRich great! I thought so too, but it wasn't in the rofi man page iirc.

**Comment by budRich** [comment]
@1ntronaut @metapodcod i have now removed i3menu from i3ass. And created a new repository for i3menu (https://github.com/budlabs/i3menu) . This new i3menu version uses a custom fork of dmenu (https://github.com/budRich/dmenu) instead of rofi. I deprecated some of the old i3menu options:  

```
anchor
fallback
include
modi
no-auto-position
options
show
target
```

and the theming is now much simpler, but all in all i think it will work as a drop in replacement for the old i3menu 97.5% of the time.

If you have installed i3ass from AUR, make sure to get the latest version of i3ass **before** installing the new version of **i3menu**:  

```
yay -S i3ass
yay -S i3menu
```

If you use i3ass-git package, you will probably need to do a clean build of that..

**Comment by budRich** [comment]
@1ntronaut   
> bugfixed: ((_o[dryrun]))  || "${_menu_command[@]}" --theme <(themefile)  

This gets rid of the segfault, but it doesn't load the generated theme (i get whatever rofi theme has been set).
rofi has messed up the theming countless times since i started using it. According to the rofi manpage:  

>In  newer rofi releases, all the theming options have been moved
       into the new theme format. They are no longer normal
         rofi options that can be passed directly  on  the  command  line
       (there are too many).
         Small  snippets  can be passed on the command line: rofi ‐theme‐
       str ’window {width: 50%;}’ to override a single
         setting. They are merged into the current theme.
         They can also be appended at the end of the rofi config file  to
       override parts of the theme.

The theme i want to apply is not a small snippet (it is a full theme file), i tried to minify it to one line, but it doesn't seem to work. And appending to the end of the rofi config file, i could not get to work either.  

I am sorry, but i'm not touching this, it is probably possible if we can get that appending to the end of the config working.

below is a autogenerated i3menu theme:  

```CSS
* {
    window-anchor:    north west;
    window-content:   [ horibox ];
    horibox-content:  [prompt,entry];
    window-width:     1920px;
    window-height:    20px;
    window-x:         0px;
    window-y:         0px;
    listview-layout:  horizontal;
    listview-lines:   50;
    entry-expand:     true;
    entry-width:      0;
    inputbar-content: [prompt,entry];
  }
  
* {
  fg:          #988d6d;
  bg:          #FFFFD8;

  activefg:    #FFFFE8;
  activehl:    #424242;
  activebg:    #8888c8;

  inactivefg:  #988d6d;
  inactivebg:  #e8eb98;

  red:         #b85c57;
  green:       #40883f;
  blue:        #0287c8;
  yellow:      #989848;
  cyan:        #4fa8a8;
  magenta:     #8888c8;

  light:       #FFFFE8;
  dark:        #424242;

  fg2:         #B8B09A;
  comment:     #B8B09A;

  bg2:         #FFFFE8;

  selectedfg:  #FFFFE8;
  selectedbg:  #8888c8;

  font1: "monospace 12";
}

*{
  background-color:    @bg2;
  border-color:        @bg2;
  text-color:          @fg;
  selbg:               @activebg;
  selfg:               @activefg;
  promptbg:            @bg2;
  promptfg:            @activehl;
  font:                @font1; 
}
/**
* i3menu rofi theme - by budRich 2018
* derived from my old Oneliner.rasi
* based on dmenu.rasi by Dave Davenport
*/

#window {
  anchor:     @window-anchor;
  location:   north west;
  padding:    2px;

  width:     @window-width;
  height:    @window-height;
  x-offset:  @window-x;
  y-offset:  @window-y;
  children:  @window-content;
}

#horibox {
  orientation: horizontal;
  children:    @horibox-content;
}

#inputbar {
  children:   @inputbar-content;
}

#listview {
  layout:     @listview-layout;
  lines:      @listview-lines;
  spacing:    5px;
  dynamic:    true;
}

#entry {
  expand:     @entry-expand;
  width:      @entry-width;
}


#element {
  padding: 0px 2px;
}

#element selected {
  text-color: @selfg;
  background-color: @selbg;
}

#prompt {
  text-color: @promptfg;
  background-color: @promptbg;
}
```

If anyone wants to experiment, create a new folder and cd into it, then `rofi -dump-config > config.rasi`  
edit the newly created config.rasi file to include the theme above (i don't know how to do this, but manpage says it is possible). to test: `rofi -config ./config.rasi`

https://github.com/budlabs/i3menu-rofi
